{% set name = "vl-convert-python" %}
{% set version = "1.9.0.post1" %}

package:
  name: {{ name }}
  version: {{ version }}

source: 
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a5b06b3128037519001166f5341ec7831e19fbd7f3a5f78f73d557ac2d5859ef
  patches:
    - 01-fix-libffi-msvc.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}     # [not win]
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - make                   # [not win]
    - cmake
    - protobuf
    - libffi  
    - jq                     # [linux and x86_64]
    - libclang               # [linux and x86_64]
    - llvmdev                # [linux and x86_64]
    - nasm                   # [win]
  host:
    - python
    - pip
    - maturin >=1.1.0,<2.0.0
    - sqlite                 
    - pkg-config           
    - libffi
    - libiconv  # [osx]
  run:
    - python
    - libzlib
    - libffi 

# Test are not run because pypdfium2 is not in the main channel
test:
  imports:
    - vl_convert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonmmease/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  description: |
          vl-convert-python is a dependency-free Python package for converting Vega-Lite chart specifications
          into static images (SVG or PNG) or Vega chart specifications.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - vl-convert-python/LICENSE
    - vl-convert-python/thirdparty_font.md        # [not arm64 and not linux]
    - vl-convert-python/thirdparty_javascript.md  # [not arm64 and not linux]
    - vl-convert-python/thirdparty_rust.yaml      # [not arm64 and not linux]
  doc_url: https://github.com/jonmmease/vl-convert/tree/main
  dev_url: https://github.com/jonmmease/vl-convert/tree/main

extra:
  recipe-maintainers:
    - jonmmease
