{% set name = "vl-convert-python" %}
{% set version = "1.9.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vl_convert_python-{{ version }}.tar.gz
  sha256: a5b06b3128037519001166f5341ec7831e19fbd7f3a5f78f73d557ac2d5859ef
  patches:
    - 01-fix-libffi-msvc.patch  # [win]

build:
  number: 0
  ignore_run_exports:
    - libcxx        # [osx]
    - libstdcxx     # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cmake
    - make                                  # [not win]
    - protobuf
    - nasm                                  # [win]
    - pkg-config
  host:
    - python
    - pip
    - maturin >=1.1.0,<2
    - sqlite {{ sqlite }}
    - zlib {{ zlib }}
    - libffi {{ libffi }}
    - libiconv {{ libiconv }}
  run:
    - python

test:
  source_files:
    - vl-convert-python/tests/
    - vl-convert-rs/tests/
  imports:
    - vl_convert
  commands:
    - pip check
    # Need pypdfium2->pdfium-binaries (which brings in chromium) to run tests_specs.py
    - pytest vl-convert-python/tests/ -v --ignore=vl-convert-python/tests/test_specs.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/vega/vl-convert
  summary: Convert Vega-Lite chart specifications to SVG, PNG, or Vega
  description: |
    vl-convert-python is a Python package for converting Vega-Lite chart
    specifications into static images (SVG, PNG, PDF) and Vega specifications.
    It provides a convenient Python interface to the vl-convert Rust library,
    enabling server-side chart rendering without a web browser.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - vl-convert-python/LICENSE
    - vl-convert-python/thirdparty_font.md
    - vl-convert-python/thirdparty_javascript.md
    - vl-convert-python/thirdparty_rust.yaml
  dev_url: https://github.com/vega/vl-convert
  doc_url: https://github.com/vega/vl-convert/tree/main/vl-convert-python

extra:
  recipe-maintainers:
    - jonmmease
